// notification_data.dart
final List<Map<String, dynamic>> notification_data = [
  {
    'id': 'n1',
    'type': 'like',
    'userName': 'Sarah Chen',
    'userImage': 'https://i.pravatar.cc/150?img=1',
    'message': 'liked your photo from Tokyo',
    'timeAgo': '2m',
    'isRead': false,
    'postImage': 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '1',
  },
  {
    'id': 'n2',
    'type': 'comment',
    'userName': 'David Kim',
    'userImage': 'https://i.pravatar.cc/150?img=4',
    'message': 'commented: "The Shibuya crossing shot is perfect! 📸"',
    'timeAgo': '5m',
    'isRead': false,
    'postImage': 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '1',
  },
  {
    'id': 'n3',
    'type': 'follow',
    'userName': 'Emma Wilson',
    'userImage': 'https://i.pravatar.cc/150?img=16',
    'message': 'started following you',
    'timeAgo': '15m',
    'isRead': false,
    'postImage': null,
    'postId': null,
  },
  {
    'id': 'n4',
    'type': 'like',
    'userName': 'Mike Torres',
    'userImage': 'https://i.pravatar.cc/150?img=3',
    'message': 'liked your journey to Barcelona',
    'timeAgo': '1h',
    'isRead': true,
    'postImage': 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '2',
  },
  {
    'id': 'n5',
    'type': 'comment',
    'userName': 'Lisa Wang',
    'userImage': 'https://i.pravatar.cc/150?img=6',
    'message': 'commented: "How long did you stay in Tokyo? Planning my trip there!"',
    'timeAgo': '2h',
    'isRead': true,
    'postImage': 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '1',
  },
  
  {
    'id': 'n8',
    'type': 'like',
    'userName': 'Pierre Dubois',
    'userImage': 'https://i.pravatar.cc/150?img=11',
    'message': 'liked your photo from Paris',
    'timeAgo': '6h',
    'isRead': true,
    'postImage': 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '3',
  },
  {
    'id': 'n9',
    'type': 'follow',
    'userName': 'Jake Thompson',
    'userImage': 'https://i.pravatar.cc/150?img=13',
    'message': 'started following you',
    'timeAgo': '8h',
    'isRead': true,
    'postImage': null,
    'postId': null,
  },
  {
    'id': 'n10',
    'type': 'comment',
    'userName': 'Sophia Lee',
    'userImage': 'https://i.pravatar.cc/150?img=14',
    'message': 'commented: "The Brooklyn Bridge shot is incredible! 🌉"',
    'timeAgo': '12h',
    'isRead': true,
    'postImage': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '4',
  },
  {
    'id': 'n12',
    'type': 'like',
    'userName': 'Emily Davis',
    'userImage': 'https://i.pravatar.cc/150?img=10',
    'message': 'and 5 others liked your journey to New York',
    'timeAgo': '1d',
    'isRead': true,
    'postImage': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    'postId': '4',
  },
  {
    'id': 'n14',
    'type': 'achievement',
    'userName': 'JourneyQ',
    'userImage': '',
    'message': 'Congratulations! You\'ve reached 100 likes on your travels 🎉',
    'timeAgo': '3d',
    'isRead': true,
    'postImage': null,
    'postId': null,
  }
];