// chat_data.dart
final List<Map<String, dynamic>> chat_data = [
  // Traveller Chats
  {
    'id': 'chat1',
    'type': 'traveller',
    'userName': 'Sarah Chen',
    'userImage': 'https://i.pravatar.cc/150?img=1',
    'lastMessage': 'The cherry blossoms in Kyoto were absolutely stunning! 🌸',
    'lastMessageTime': '2m',
    'isOnline': true,
    'unreadCount': 2,
    'messages': [
      {
        'id': 'm1',
        'senderId': 'user',
        'message': 'Hey Sarah! How was your trip to Japan?',
        'timestamp': '10:30 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm2',
        'senderId': 'sarah',
        'message': 'It was incredible! The culture, food, everything was amazing 😍',
        'timestamp': '10:32 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm4',
        'senderId': 'user',
        'message': 'Wow! That temple looks amazing. Which city is this?',
        'timestamp': '10:35 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm5',
        'senderId': 'sarah',
        'message': 'The cherry blossoms in Kyoto were absolutely stunning! 🌸',
        'timestamp': '10:38 AM',
        'isRead': false,
        'messageType': 'text',
      },
      {
        'id': 'm6',
        'senderId': 'sarah',
        'message': 'You should definitely plan a trip there!',
        'timestamp': '10:38 AM',
        'isRead': false,
        'messageType': 'text',
      },
    ],
  },
  {
    'id': 'chat2',
    'type': 'traveller',
    'userName': 'David Kim',
    'userImage': 'https://i.pravatar.cc/150?img=4',
    'lastMessage': 'Thanks for the Barcelona recommendations!',
    'lastMessageTime': '15m',
    'isOnline': false,
    'unreadCount': 0,
    'messages': [
      {
        'id': 'm7',
        'senderId': 'david',
        'message': 'Hey! I saw your Barcelona post. Any hidden gems you\'d recommend?',
        'timestamp': '9:15 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm8',
        'senderId': 'user',
        'message': 'Absolutely! Park Güell is a must-see, but go early to avoid crowds',
        'timestamp': '9:18 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm9',
        'senderId': 'user',
        'message': 'Also try the tapas at Cal Pep - it\'s incredible but tiny!',
        'timestamp': '9:18 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm10',
        'senderId': 'david',
        'message': 'Thanks for the Barcelona recommendations!',
        'timestamp': '9:25 AM',
        'isRead': true,
        'messageType': 'text',
      },
    ],
  },
  {
    'id': 'chat3',
    'type': 'traveller',
    'userName': 'Emma Wilson',
    'userImage': 'https://i.pravatar.cc/150?img=16',
    'lastMessage': 'Would love to collaborate on a NYC food tour!',
    'lastMessageTime': '1h',
    'isOnline': true,
    'unreadCount': 1,
    'messages': [
      {
        'id': 'm11',
        'senderId': 'emma',
        'message': 'Hi! I\'m planning a food tour in NYC next month',
        'timestamp': '8:30 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm12',
        'senderId': 'emma',
        'message': 'Would love to collaborate on a NYC food tour!',
        'timestamp': '8:31 AM',
        'isRead': false,
        'messageType': 'text',
      },
    ],
  },
  {
    'id': 'chat4',
    'type': 'traveller',
    'userName': 'Mike Torres',
    'userImage': 'https://i.pravatar.cc/150?img=3',
    'lastMessage': 'The sunset photos from Santorini are breathtaking!',
    'lastMessageTime': '3h',
    'isOnline': false,
    'unreadCount': 0,
    'messages': [
      {
        'id': 'm13',
        'senderId': 'mike',
        'message': 'Just saw your Greece photos! 📸',
        'timestamp': 'Yesterday',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm14',
        'senderId': 'mike',
        'message': 'The sunset photos from Santorini are breathtaking!',
        'timestamp': 'Yesterday',
        'isRead': true,
        'messageType': 'text',
      },
    ],
  },

  // Marketplace Chats
  {
    'id': 'chat5',
    'type': 'marketplace',
    'userName': 'TravelGear Pro',
    'userImage': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    'lastMessage': 'Your hiking backpack order has been shipped! 📦',
    'lastMessageTime': '5m',
    'isOnline': true,
    'unreadCount': 1,
    'isVerified': true,
    'messages': [
      {
        'id': 'm15',
        'senderId': 'user',
        'message': 'Hi! Is the 40L hiking backpack still available?',
        'timestamp': '2:00 PM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm16',
        'senderId': 'store',
        'message': 'Yes! It\'s available in black and forest green. Which color would you prefer?',
        'timestamp': '2:02 PM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm17',
        'senderId': 'user',
        'message': 'Forest green please! Can you send me more photos?',
        'timestamp': '2:05 PM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm19',
        'senderId': 'store',
        'message': 'Your hiking backpack order has been shipped! 📦',
        'timestamp': '2:10 PM',
        'isRead': false,
        'messageType': 'text',
      },
    ],
  },
  {
    'id': 'chat6',
    'type': 'marketplace',
    'userName': 'Camera Rentals NYC',
    'userImage': 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    'lastMessage': 'Camera is ready for pickup tomorrow at 10 AM',
    'lastMessageTime': '30m',
    'isOnline': false,
    'unreadCount': 0,
    'isVerified': true,
    'messages': [
      {
        'id': 'm20',
        'senderId': 'user',
        'message': 'I need to rent a DSLR camera for a week-long trip',
        'timestamp': '1:00 PM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm21',
        'senderId': 'store',
        'message': 'We have Canon EOS R5 and Sony A7 IV available. Both excellent for travel photography!',
        'timestamp': '1:15 PM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm22',
        'senderId': 'store',
        'message': 'Camera is ready for pickup tomorrow at 10 AM',
        'timestamp': '1:30 PM',
        'isRead': true,
        'messageType': 'text',
      },
    ],
  },
  {
    'id': 'chat7',
    'type': 'marketplace',
    'userName': 'Local Guide Services',
    'userImage': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    'lastMessage': 'Perfect! I can show you the best hidden spots in Paris 🗼',
    'lastMessageTime': '2h',
    'isOnline': true,
    'unreadCount': 2,
    'isVerified': true,
    'messages': [
      {
        'id': 'm23',
        'senderId': 'user',
        'message': 'Looking for a local guide in Paris for 2 days',
        'timestamp': '11:00 AM',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm24',
        'senderId': 'guide',
        'message': 'Perfect! I can show you the best hidden spots in Paris 🗼',
        'timestamp': '11:15 AM',
        'isRead': false,
        'messageType': 'text',
      },
      {
        'id': 'm25',
        'senderId': 'guide',
        'message': 'When are you visiting? I have availability next week',
        'timestamp': '11:16 AM',
        'isRead': false,
        'messageType': 'text',
      },
    ],
  },
  {
    'id': 'chat8',
    'type': 'marketplace',
    'userName': 'Adventure Gear Shop',
    'userImage': 'https://images.unsplash.com/photo-1544966503-7cc1834f78ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80',
    'lastMessage': 'We have a 20% discount on camping gear this week!',
    'lastMessageTime': '4h',
    'isOnline': false,
    'unreadCount': 0,
    'isVerified': false,
    'messages': [
      {
        'id': 'm26',
        'senderId': 'store',
        'message': 'Hi! Thanks for your interest in our camping equipment',
        'timestamp': 'Yesterday',
        'isRead': true,
        'messageType': 'text',
      },
      {
        'id': 'm27',
        'senderId': 'store',
        'message': 'We have a 20% discount on camping gear this week!',
        'timestamp': 'Yesterday',
        'isRead': true,
        'messageType': 'text',
      },
    ],
  },
];